package java8;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

public class DemoMap {
    public static void main(String[] args) {
        ArrayList<String> fruit = new ArrayList<>();
        fruit.add("Apple");
        fruit.add("Banana");
        fruit.add("Orange");
        fruit.add("mango");
        fruit.add("kiwi");
        System.out.println("List of fruit-" + fruit);

        List list = fruit.stream()
                .map(s -> s.length())
                .collect(Collectors.toList());
        System.out.println("List generated by map-" + list);

//        Output:
//
//        List of fruit-[Apple, Banana, Orange, mango, kiwi]
//        List generated by map-[5, 6, 6, 5, 4]
    }
}
